### ISSUE TITLE
Unknown loss function: multilabel_bce

### ISSUE THREAD

**Issue by lostanlen** [BirdVox/birdvoxclassify#6]
Loading the TaxoNet leads to an error in `keras.models.load_model`
The `multilabel_bce` does not exist in this repository. It appears in the `localmodule` of `cramer2020icassp`

Traceback below:

```python
>>> X = keras.models.load_model("/Users/vl238/miniconda3/envs/bvd04/lib/python3.6/site-packages/birdvoxclassify-0.1.1-py3.6.egg/birdvoxclassify/resources/models/birdvoxclassify-taxonet_tv1hierarchical-7896de0a208a341730b315e90bf3e30f.h5")
2020-11-02 15:54:58.575767: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-11-02 15:54:58.607587: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7faa21339060 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-02 15:54:58.607617: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vl238/miniconda3/envs/bvd04/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 182, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/Users/vl238/miniconda3/envs/bvd04/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 194, in load_model_from_hdf5
    training_config, custom_objects))
  File "/Users/vl238/miniconda3/envs/bvd04/lib/python3.6/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 217, in compile_args_from_training_config
    loss = _deserialize_nested_config(losses.deserialize, loss_config)
  File "/Users/vl238/miniconda3/envs/bvd04/lib/python3.6/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 262, in _deserialize_nested_config
    for k, v in config.items()
  File "/Users/vl238/miniconda3/envs/bvd04/lib/python3.6/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 262, in <dictcomp>
    for k, v in config.items()
  File "/Users/vl238/miniconda3/envs/bvd04/lib/python3.6/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 258, in _deserialize_nested_config
    return deserialize_fn(config)
  File "/Users/vl238/miniconda3/envs/bvd04/lib/python3.6/site-packages/tensorflow/python/keras/losses.py", line 1854, in deserialize
    printable_module_name='loss function')
  File "/Users/vl238/miniconda3/envs/bvd04/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 378, in deserialize_keras_object
    'Unknown ' + printable_module_name + ': ' + object_name)
ValueError: Unknown loss function: multilabel_bce
```

**Comment by jtcramer** [comment]
The model should be loaded using `compile=False`, I must've forgotten to change the test. Good catch!

**Comment by jtcramer** [comment]
Oh whoops, this was a local shell. But yeah, because we're saving the whole model, it also saves all of the optimization stuff (which in the future we can discard) which Keras attempts to reinstantiate by default (with the default `compile=True`).
